### ISSUE TITLE
MyAnimelist Sync?

### ISSUE THREAD

**Issue by siker498** [vapormusic/AnimeXStream#1]
Your Fork is updated more often and Im wondering if adding MAL is possible on your end?

**Comment by vapormusic** [comment]
I can't promise that because I'm pretty busy but I will consider it I have the time to.

**Comment by siker498** [comment]
ok thx, one more request if possible, an option to disable gestures in the video player? Not everyone wants to control brightness and volume from there.

**Comment by vapormusic** [comment]
@siker498 https://github.com/vapormusic/AnimeXStream/releases/tag/v3.0.2 should be it
