### ISSUE TITLE
Improvements and Bug Fixes

### ISSUE THREAD

**Issue by siker498** [vapormusic/AnimeXStream#2]
Hey! Thanks for taking my suggestion about MAL Sync!

There is a subreddit for the original fork of Anime X Stream, and they are starting to use yours due to having more features. 

Here are some improvements and bug fixes you could add if possible!

- In addition to MAL , Anilist would also be great.

- When signing in to either MAL or Anilist, Watching/Planning/Completed episodes from these services get synced with Anime X stream, (The favorites tab would be a great place for adding the Watching/Planning/Completed sync.)

- Move the search button to the bottom navigation bar. 

- Remove the Useless heart icon 

Bug Fixes:

- Remove or fix Anime Pahe 

- Current MAL Sync not working. (watching episodes doesn't sync with MAL)

Don't feel rushed! these are just suggestions from me and the subreddit.

**Comment by siker498** [comment]
Plus a check for updates button in settings

**Comment by vapormusic** [comment]
Nahh, it works for me....  btw i don't update this often ....

**Comment by an1k3tt** [comment]
Whenever i update my previous favorites are gone....is there anything I'm doing wrong...which file should i use for update...is the universal one the real..pls help.

**Comment by vapormusic** [comment]
> Whenever i update my previous favorites are gone....is there anything I'm doing wrong...which file should i use for update...is the universal one the real..pls help.

Sorry, this is a beta so things are pretty buggy.... it will delete your favorites

**Comment by an1k3tt** [comment]
> > Whenever i update my previous favorites are gone....is there anything I'm doing wrong...which file should i use for update...is the universal one the real..pls help.
> 
> Sorry, this is a beta so things are pretty buggy.... it will delete your favorites

No need to apologize....after all you are the one is providing smooth anime experience for weeb like me😭Thank you🙇‍♂️
